### ISSUE TITLE
understanding Usagi search process

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Usagi#12]
Please, look on this table
![image](https://cloud.githubusercontent.com/assets/8568959/8333769/2f2934f2-1a9d-11e5-9507-30136793282e.png)
"Should_be_concepts" seems to be closer by their spelling than proposed by usagi.
I want to know about search algorithm to understand what I can expect from usagi-mapping, and expect where and why will be inaccurate mapping.
So please explain why we have such inaccuracies here or give a link where search-algoritm we use here is explained.
Thanks.

**Comment by schuemie** [comment]
Usagi uses the [Lucene](https://lucene.apache.org/) free text search engine, which basically implements a bag-of-words TF*IDF cosine matching scheme.In short: Usagi matches on words, and gives more weight to words that appear in fewer concepts (ie that are more unique).

To account for different variations of the same words, Usagi also uses the [Porter stemmer](http://people.ischool.berkeley.edu/~hearst/irbook/porter.html) to reduce words to their stem. For example, 'children' is reduced to 'child' before matching.

In the examples you provided, the stemmer failed. Usagi could not see that 'streptococcal' was related to 'streptococcus', or that 'infant' was related to 'infantile'.

**Comment by dimshitc** [comment]
Ok. I've get. Thanks.

**Comment by schuemie** [comment]
Hi @dimshitc 

I'm experimenting with using n-grams instead of words. N-grams are combinations of n-letters, so for example the term 'infant' will generate the following 3-grams:
- inf
- nfa
- fan
- ant

Still using the TF*IFD cosine matching, Usagi will now use these features (2-grams and 3-grams) to match.

Could you give this a try? I created a [new release](https://github.com/OHDSI/Usagi/releases/tag/v0.3.1.x). You'll need to rebuild the index. Performance will be slower and the index will be bigger, but Usagi should be far more robust against variations in words.
