### ISSUE TITLE
Usagi_v0.3.3 and Usagi_v1.0.0x make different results

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Usagi#24]
Hi, Martijn,

We have tested out "Usagi_v1.0.0x.jar" comparing results with the previous run of "Usagi_v0.3.3.jar" on the same data. Used only SNOMED in both cases to make clear comparison ( to avoid search by source concepts mapped to standard concepts feature).
We are wondering how is it possible that we get different results?
Please, look on a file attached:
"Old was better" spreadsheet - case when Usagi_v0.3.3 made a better matching
"New is better" - when Usagi_v1.0.0x results are better.
fields: source_name - the name of concepts of the source_dateset
fields with "old" - version Usagi_v0.3.3 results, with "new" - Usagi_v1.0.0x.

[Usagi_v0.3.3_vs_Usagi_v1.0.0_comparison.xlsx](https://github.com/OHDSI/Usagi/files/902483/Usagi_v0.3.3_vs_Usagi_v1.0.0_comparison.xlsx)

**Comment by schuemie** [comment]
Thanks for testing out the new version! 

Some differences in mappings are expected because Usagi uses tf.idf weighting. In other words trigrams are inversely weighted by how many terms have the trigram. And now that source terms have been added to the index, the statistics of the trigrams have changed dramatically.

That being said, I'm not able to reproduce all of the behavior you report. Your first example, 'banana allergy', still returns 'Allergy to banana' as best match, which is what you'd expect since its an almost perfect match in trigrams.

Could you tell me which version of the vocab you're using? What were the specific filters you applied in your search?

**Comment by dimshitc** [comment]
Version of vocabulary - v5.0 30-DEC-16
Filter - vocabulary_id ='SNOMED', concept_class_id = 'Clinical Finding',

"And now that source terms have been added to the index, the statistics of the trigrams have changed dramatically."
The thing is that we downloaded from Athena **only** SNOMED (without any "source" vocabularies like "ICDs"), that's why I'm confusing, why we have different results in different versions of usagi and especially in those "Banana allergy" case, when the newest version find "Allergic disposition" instead of obvious "Allergy to banana"

**Comment by schuemie** [comment]
Would it be possible to somehow share the exact Athena files you used? Otherwise it will be impossible for me to replicate this issue.
