### ISSUE TITLE
Missing domain column

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Usagi#27]
In the new version the domain column is missing which we used to determine the table to push the data to.

Can this be put back in?

**Comment by schuemie** [comment]
I'm not sure I agree that is the right thing to do. The domain should be learned from the vocab at ETL time, to make 100% sure the data in the CDM lines up with the data in the vocab inside the CDM.

I know that often that will be the same vocab as used in Usagi, since you would want to check if there are any important changes affecting the mapping, but I could also imagine you don't always run it through Usagi at every vocab update.

**Comment by PRijnbeek** [comment]
Sure I see your point even though we will always run through Usagi to check the mappings of a new vocab update (the new apply mappings is very handy for that). Furthermore, Achilles Heel checks need to be signed off anyway that will show problems with vocab versions

We now make txt files for JCDMBuilder to import to the database. Currently, there is no connection needed to the database for the ET part of the ETL. This change would mean this needs to be added now. I will check how we could do this, but for now it is much easier to just have the domain in the Usagi file as was the case in the previous version.

I could use an older version of Usagi for now (although I like the new features), or fork and add the column myself of course if you do want this in master.
