### ISSUE TITLE
Index rebuilt and concepts are missing

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Usagi#33]
Thanks @schuemie for the heads up on the newer version of Usagi. I just installed the newest version and rebuilt the index. I noticed the standard concepts for inpatient and outpatient are missing from the Visit vocabulary. I also do not have any Gender or PCORNet concepts. Gender concepts are automatically pushed with the vocabularies. And we did select PCORNet as one of our vocabularies. Any ideas?

![screen shot 2017-08-31 at 1 46 07 pm](https://user-images.githubusercontent.com/22457958/29942456-2b806768-8e53-11e7-9a06-e7a2bb0bf7ea.png)

**Comment by schuemie** [comment]
Hi @MelaniePhilofsky ,

Can you confirm that the missing visit  concepts isn't due to the search query you used (can't see it in your screenshot). Here's what I see when I search with 'patient':
![usagi](https://user-images.githubusercontent.com/6713328/29956541-150965ee-8ee8-11e7-920e-3486546935c9.png)

I also can't seem to find a problem with gender concepts. Which vocabulary version are you using?

PCORNet concepts aren't standard concepts, so that is the reason why they don't appear in Usagi. What would be the use case for mapping to PCORNet concepts?

**Comment by MelaniePhilofsky** [comment]
Thanks for getting back to me @schuemie ,
I rebuilt the index after my post and that fixed the gender and visit issues.
As for PCORNet concepts, I thought that with the addition of the Standard Concept column was also the addition of non-standard concepts. And PCORNet is an option from the Vocabulary drop down in Usagi. We provide datasets to our local investigators. Many of these researchers want to know every race a person claims. OHDSI and the US government limit that list to 5 chosen races. Our data sources do not. So we have many persons who have values for "multiracial", "unknown" or "other". The PCORNet value set provides for the most accurate representation of our source data (this is also true in the ethnicity & gender domains).  Is this a strong enough use case to include the PCORNet vocabulary?

**Comment by schuemie** [comment]
The reason why PCORNet is in the Usagi drop down is because there are 2 concepts that are marked as 'standard' from that vocabulary: 'Residential facility' (44814701) and 'Residential facility' (44814680) (the first is a discharge status, the second an admitting source).

If I understand correctly you are advocating for elevating some PCORNet concepts to standard concepts, specifically the concepts related to race:

```sql
SELECT * FROM concept WHERE vocabulary_id = 'PCORNet' AND concept_class_id = 'Race';
```

concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
44814655 | Asian | Observation | PCORNet | Race |   | Race-02 | 1970-01-01 | 2099-12-31
44814659 | Multiple race | Observation | PCORNet | Race |   | Race-06 | 1970-01-01 | 2099-12-31
44814654 | American Indian or Alaska Native | Observation | PCORNet | Race |   | Race-01 | 1970-01-01 | 2099-12-31
44814658 | White | Observation | PCORNet | Race |   | Race-05 | 1970-01-01 | 2099-12-31
44814657 | Native Hawaiian or Other Pacific Islander | Observation | PCORNet | Race |   | Race-04 | 1970-01-01 | 2099-12-31
44814660 | Refuse to answer | Observation | PCORNet | Race |   | Race-07 | 1970-01-01 | 2099-12-31
44814656 | Black or African American | Observation | PCORNet | Race |   | Race-03 | 1970-01-01 | 2099-12-31

I think most of these are covered by the current standard concepts:
```sql
SELECT * FROM concept WHERE concept_class_id = 'Race' AND standard_concept = 'S';
```

concept_id | concept_name | domain_id | vocabulary_id | concept_class_id | standard_concept | concept_code | valid_start_date | valid_end_date | invalid_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
38003605 | Haitian | Race | Race | Race | S | 3.08 | 1970-01-01 | 2099-12-31
38003606 | Jamaican | Race | Race | Race | S | 3.09 | 1970-01-01 | 2099-12-31
38003607 | Tobagoan | Race | Race | Race | S | 3.10 | 1970-01-01 | 2099-12-31
38003608 | Trinidadian | Race | Race | Race | S | 3.11 | 1970-01-01 | 2099-12-31
38003609 | West Indian | Race | Race | Race | S | 3.12 | 1970-01-01 | 2099-12-31
38003610 | Polynesian | Race | Race | Race | S | 4.01 | 1970-01-01 | 2099-12-31
38003611 | Micronesian | Race | Race | Race | S | 4.02 | 1970-01-01 | 2099-12-31
38003612 | Melanesian | Race | Race | Race | S | 4.03 | 1970-01-01 | 2099-12-31
38003613 | Other Pacific Islander | Race | Race | Race | S | 4.04 | 1970-01-01 | 2099-12-31
38003614 | European | Race | Race | Race | S | 5.01 | 1970-01-01 | 2099-12-31
38003615 | Middle Eastern or North African | Race | Race | Race | S | 5.02 | 1970-01-01 | 2099-12-31
38003616 | Arab | Race | Race | Race | S | 5.03 | 1970-01-01 | 2099-12-31
8515 | Asian | Race | Race | Race | S | 2 | 1970-01-01 | 2099-12-31
8516 | Black or African American | Race | Race | Race | S | 3 | 1970-01-01 | 2099-12-31
8527 | White | Race | Race | Race | S | 5 | 1970-01-01 | 2099-12-31
8557 | Native Hawaiian or Other Pacific Islander | Race | Race | Race | S | 4 | 1970-01-01 | 2099-12-31
8657 | American Indian or Alaska Native | Race | Race | Race | S | 1 | 1970-01-01 | 2099-12-31
38003572 | American Indian | Race | Race | Race | S | 1.01 | 1970-01-01 | 2099-12-31
38003573 | Alaska Native | Race | Race | Race | S | 1.02 | 1970-01-01 | 2099-12-31
38003574 | Asian Indian | Race | Race | Race | S | 2.01 | 1970-01-01 | 2099-12-31
38003575 | Bangladeshi | Race | Race | Race | S | 2.02 | 1970-01-01 | 2099-12-31
38003576 | Bhutanese | Race | Race | Race | S | 2.03 | 1970-01-01 | 2099-12-31
38003577 | Burmese | Race | Race | Race | S | 2.04 | 1970-01-01 | 2099-12-31
38003578 | Cambodian | Race | Race | Race | S | 2.05 | 1970-01-01 | 2099-12-31
38003579 | Chinese | Race | Race | Race | S | 2.06 | 1970-01-01 | 2099-12-31
38003580 | Taiwanese | Race | Race | Race | S | 2.07 | 1970-01-01 | 2099-12-31
38003581 | Filipino | Race | Race | Race | S | 2.08 | 1970-01-01 | 2099-12-31
38003582 | Hmong | Race | Race | Race | S | 2.09 | 1970-01-01 | 2099-12-31
38003583 | Indonesian | Race | Race | Race | S | 2.10 | 1970-01-01 | 2099-12-31
38003584 | Japanese | Race | Race | Race | S | 2.11 | 1970-01-01 | 2099-12-31
38003585 | Korean | Race | Race | Race | S | 2.12 | 1970-01-01 | 2099-12-31
38003586 | Laotian | Race | Race | Race | S | 2.13 | 1970-01-01 | 2099-12-31
38003587 | Malaysian | Race | Race | Race | S | 2.14 | 1970-01-01 | 2099-12-31
38003588 | Okinawan | Race | Race | Race | S | 2.15 | 1970-01-01 | 2099-12-31
38003589 | Pakistani | Race | Race | Race | S | 2.16 | 1970-01-01 | 2099-12-31
38003590 | Sri Lankan | Race | Race | Race | S | 2.17 | 1970-01-01 | 2099-12-31
38003591 | Thai | Race | Race | Race | S | 2.18 | 1970-01-01 | 2099-12-31
38003592 | Vietnamese | Race | Race | Race | S | 2.19 | 1970-01-01 | 2099-12-31
38003593 | Iwo Jiman | Race | Race | Race | S | 2.20 | 1970-01-01 | 2099-12-31
38003594 | Maldivian | Race | Race | Race | S | 2.21 | 1970-01-01 | 2099-12-31
38003595 | Nepalese | Race | Race | Race | S | 2.22 | 1970-01-01 | 2099-12-31
38003596 | Singaporean | Race | Race | Race | S | 2.23 | 1970-01-01 | 2099-12-31
38003597 | Madagascar | Race | Race | Race | S | 2.24 | 1970-01-01 | 2099-12-31
38003598 | Black | Race | Race | Race | S | 3.01 | 1970-01-01 | 2099-12-31
38003599 | African American | Race | Race | Race | S | 3.02 | 1970-01-01 | 2099-12-31
38003600 | African | Race | Race | Race | S | 3.03 | 1970-01-01 | 2099-12-31
38003601 | Bahamian | Race | Race | Race | S | 3.04 | 1970-01-01 | 2099-12-31
38003602 | Barbadian | Race | Race | Race | S | 3.05 | 1970-01-01 | 2099-12-31
38003603 | Dominican | Race | Race | Race | S | 3.06 | 1970-01-01 | 2099-12-31
38003604 | Dominica Islander | Race | Race | Race | S | 3.07 | 1970-01-01 | 2099-12-31

The only ones currently missing are 'Multiple race' and 'Refuse to answer'. 

Whether I accept the use case or not is irrelevant, it is up to the vocab folks to decide which concepts are to be used as standard.

@cgreich : what say you?

**Comment by MelaniePhilofsky** [comment]
@schuemie,

I am not advocating to elevate the non-standard PCORNet concepts to standard concept status. @cgreich and I have already been through that discussion :)  I would like to advocate for the inclusion of some non-standard PCORNet concepts into Usagi, so I can efficiently meet our use case. Specifically:

 4481469 multiple race
44814649 other
44814653 unknown
44814660 refuse to answer

Thanks,
Melanie

**Comment by schuemie** [comment]
I'm sorry, I still don't understand why you want to map to concepts that are non-standard and are therefore by definition not allowed to be used in the CDM.

If you did want to do this, you could modify the ATHENA input files, and set these specific concepts to 'standard' before building the Usagi index. That would be the easiest way to let Usagi know what valid target concepts are.

**Comment by cgreich** [comment]
@MelaniePhilofsky:

This race discussion keeps coming back. We should probably add some language in the documentation.

"Other", "Unknown" and "Refuse to answer", as well as "Whatever", "Get off my back", "Have no clue", "Bullshit" etc. all have one meaning for an analytic application: We don't know the race. The proper representation in OMOP is concept_id=0. Which is why we call them "flavors of null". Multiple race I would personally argue is the same as well. Since we are all from Kenya, and the races are biologically very lose definitions, we all have multiple. And none is predominant. Which means, the concept_id should be 0 as well.

**Comment by MelaniePhilofsky** [comment]
I agree with you, @cgreich However, our shop delivers data to our on-campus investigators and researchers. Our customers know that our sources have up to data 5 columns for race and include the standard American government values plus variations of "other", "unknown", "refused to answer", etc. And our customers want this data (almost every data request asks for this, I would say every, but I haven't reviewed every data request). We could pull this data from the race_source_value, but then we end up querying some source_value fields  and some concept_id fields and it becomes a huge, confusing mess. I'm not asking to make these standard concepts. I was just hoping we could add these non-standard concepts to Usagi. The folks at PEDSnet got them into the OMOP CDM, I would like them in Usagi too :)

**Comment by cgreich** [comment]
@MelaniePhilofsky:

I need to straighten your spine here a little bit, Melanie. :)  Look: I am having these debates all the time. It's very simple. **We as a community** decide what goes into the CDM, and not the customer. They have the source_value field to make them happy. The representation of data is standardized. If we don't have knowledge, but know there is a record, the concept_id is 0. Period. And if somebody wants to change that - totally ok. But they need to bring a use case. If they can explain how an analytic would gain anything from knowing whether the race was "refused to answer" or "unknown" (which is nonsense anyway), then I am happy to consider. But nobody has ever produced such a use case, which means, the concept_id is 0. Done.

Another argument for you: We want to support remote studies. That means, that the data **have** to conform to the standard, otherwise you cannot rely blindly on the results to be correct, but need to second-guess them every single time. If you want that, you don't need a CDM. Just use the native data.
