### ISSUE TITLE
Change in columns

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Usagi#34]
We recently updated Usagi from a rather old version. Now the conceptName, conceptClass, vocabulary, and domain columns are no longer present. Our EHR data contains a lot of custom coding and we use the mentioned columns for QC on mappings. Any chance these could be added back in?

The following columns are also no longer present, but not of concern: term, conceptCode, validStartDate, validEndDate, invalidReason, and additionInformation are also missing.

Thanks,
Melanie

**Comment by schuemie** [comment]
You can export the mapping using File --> Export source_to_concept_map. That should give you the fields you mention.

**Comment by MelaniePhilofsky** [comment]
@schuemie,
 
Unfortunately, the export source_to_concept_map still doesn't give me conceptName, conceptClass, and domain fields. It adds the source_concept_id, target_vocabulary, valid_start_date, valid_end_date, and invalid_reason.

**Comment by schuemie** [comment]
I would actually think the best place to review a mapping is in Usagi itself, because it also allows the reviewer to explore the parents and children of the target concept. The social life of a target concept is just as important as other attributes such as the name and domain!

But adding an extra report is not much work, so I've added it in [this new release](https://github.com/OHDSI/Usagi/releases/tag/v1.1.3). I hope that meets your requirements.

This should also resolve [this issue](https://github.com/OHDSI/Usagi/issues/27).

**Comment by MelaniePhilofsky** [comment]
Great, thanks @schuemie ! I agree, family is important. I do all the semantic mapping & review in Usagi.  Then I have a 2nd set of eyes give it a quick once over for glaring errors before loading the concepts.
