### ISSUE TITLE
Index builder requires invalid_reason to be in last column

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Usagi#52]
Through some trial and error, I found that it is required for the `invalid_reason` to be in the last column. Otherwise the value is an empty string and not `null`. The latter is required to add a concept to the index.

For example, see this custom CONCEPT.csv file, with an empty invalid reason (two subsequent tabs).
```
concept_id	concept_name	concept_code	vocabulary_id	domain_id	concept_class_id	valid_start_date	valid_end_date	invalid_reason	standard_concept
1	Tissue	TISSUE	tissue	Observation	Level-0	1970-01-01	2099-12-31		S
```

When using this file to build the index, none of the concepts are added to the index. This is probably due to this null check:
https://github.com/OHDSI/Usagi/blob/4d2d2038cdbfc67c957cdba5a6b208041a9802cc/src/org/ohdsi/usagi/indexBuilding/BerkeleyDbBuilder.java#L53-L55

When I replaced line 54 to check for empty string (`.equals("")`), the Berkely builder does work for my file. This did not solve the whole issue as the Lucene index builder still did not build an index.

I solved my issue by just moving the invalid_reason to the last column. However, this is not trivial to discover. Any ideas as why the Lucene index does not find the concepts when `invalid_reason=""`?

**Comment by schuemie** [comment]
Well, in case you're interested the reason the concepts don't get added anyway is because there's a later check whether concept.invalidReason == null, and concept.invalidReason is populated using the Row object, so has the same issue.

The real inconsistency is that if the last column of an Athena file is empty it is turned into a null instead of just an empty string. I'll fix this root problem and change the downstream issues arising from that fix. Should have a new version up shortly.

Just out of curiosity: how did you get a CONCEPT file where invalid_reason is not the last column?

**Comment by schuemie** [comment]
@MaximMoinat : could you give [this new release](https://github.com/OHDSI/Usagi/releases/tag/v1.2.1) a try?

**Comment by MaximMoinat** [comment]
Thanks for fixing this! It works as expected now.

> Just out of curiosity: how did you get a CONCEPT file where invalid_reason is not the last column?

I made a custom concept list, composed out of [Oncotree concepts](http://oncotree.mskcc.org/#/home) to be specific. In the end I just moved the invalid_reason to the end.
