### ISSUE TITLE
Add functionality for updating existing mappings

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Usagi#6]
Usagi currently is designed for creating a mapping from scratch. However, it could also be useful when a mapping needs updating, for example when the source coding system or vocabulary have been updated. Usagi could flag target concepts that have become invalid, new source codes that need mapping, and new target concepts that might be better matches than the current choices.

**Comment by cgreich** [comment]
Martijn.

Yes, That would be good. IN addition:
- Use the replace/update relationship to point to a new fresh potential match, or to discourage it
- If a new mapping comes up on top of an existing one, point that out and let the user decide. 
- Create a memory of what's been already reviewed, so folks wouldn't always have to start from scratch.
- Use hierarchical information for mapping. Currently, everything hangs off of the concept_name. But that creates sometimes horrible mappings, because the children in the two vocabularies are drastically different, adn therefore a seemingly close mapping should be rejected. I can bring good examples.
- For drug mappings, create a much more refined suggestion engine based on the combination of mapped ingredients, strength and form.

**Comment by cgreich** [comment]
One more, which is actually very important:
- Characterize the target concepts. Make sure they have a "social life", meaning, they have ancestors and descendents, and the ancestors and descendants are precise (not close to the top guy). Also, lateral relationships also speak in favor of a meaningful concepts. I give you an exampe:
SNOMED 45757700 "Congenital anomaly of cardiac chambers and connections" which sounds like a perfectly fine concept is a so-called Navigational Concept and has no descendants. Which means, pretty useless.
